doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidBinaryType

    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Domain:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Domain'
                        prefix: 'App\Domain'
                        alias: Domain
                dql:
                    string_functions:
                        UUID: DoctrineExtensions\Query\Mysql\Uuid
