# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Domain\Product\ProductRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\ProductRepository'
    App\Domain\Category\CategoryRepositoryInterface: '@App\Infrastructure\Persistence\Doctrine\CategoryRepository'

    App\Infrastructure\Notification\NotifierInterface:
        alias: App\Infrastructure\Notification\EmailNotifier
        public: false


    App\Infrastructure\Notification\EmailNotifier:
        arguments:
            $mailer: '@mailer.mailer'
            $twig: '@twig'
        tags: [ 'app.notifier' ]

    App\Infrastructure\Notification\:
        resource: '../src/Infrastructure/Notification'
        exclude:
            - '../src/Infrastructure/Notification/NotificationDTO.php'
        tags: [ 'app.notifier' ]

        # 2) Handler musi wiedzieć, skąd brać iterable $notifiers
    App\Infrastructure\MessageHandler\ProductCreatedMessageHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $notifiers: !tagged_iterator app.notifier

    App\Infrastructure\MessageHandler\ProductUpdateMessageHandler:
        tags: [ 'messenger.message_handler' ]
        arguments:
            $notifiers: !tagged_iterator app.notifier
